photologue/urls.py
from django.urls import path, re_path, reverse_lazy
from django.views.generic import RedirectView

from .views import (GalleryArchiveIndexView, GalleryDateDetailView, GalleryDayArchiveView, GalleryDetailView,
                    GalleryListView, GalleryMonthArchiveView, GalleryYearArchiveView, PhotoArchiveIndexView,
                    PhotoDateDetailView, PhotoDayArchiveView, PhotoDetailView, PhotoListView, PhotoMonthArchiveView,
                    PhotoYearArchiveView)

"""NOTE: the url names are changing. In the long term, I want to remove the 'pl-'
prefix on all urls, and instead rely on an application namespace 'photologue'.

At the same time, I want to change some URL patterns, e.g. for pagination. Changing the urls
twice within a few releases, could be confusing, so instead I am updating URLs bit by bit.

The new style will coexist with the existing 'pl-' prefix for a couple of releases.

"""

app_name = 'photologue'
urlpatterns = [
    re_path(r'^gallery/(?P<year>\d{4})/(?P<month>[0-9]{2})/(?P<day>\w{1,2})/(?P<slug>[\-\d\w]+)/$',
            GalleryDateDetailView.as_view(month_format='%m'),
            name='gallery-detail'),
    re_path(r'^gallery/(?P<year>\d{4})/(?P<month>[0-9]{2})/(?P<day>\w{1,2})/$',
            GalleryDayArchiveView.as_view(month_format='%m'),
            name='gallery-archive-day'),
    re_path(r'^gallery/(?P<year>\d{4})/(?P<month>[0-9]{2})/$',
            GalleryMonthArchiveView.as_view(month_format='%m'),
            name='gallery-archive-month'),
    re_path(r'^gallery/(?P<year>\d{4})/$',
            GalleryYearArchiveView.as_view(),
            name='pl-gallery-archive-year'),
    path('gallery/',
         GalleryArchiveIndexView.as_view(),
         name='pl-gallery-archive'),
    path('',
         RedirectView.as_view(
             url=reverse_lazy('photologue:pl-gallery-archive'), permanent=True),
         name='pl-photologue-root'),
    re_path(r'^gallery/(?P<slug>[\-\d\w]+)/$',
            GalleryDetailView.as_view(), name='pl-gallery'),
    path('gallerylist/',
         GalleryListView.as_view(),
         name='gallery-list'),

    re_path(r'^photo/(?P<year>\d{4})/(?P<month>[0-9]{2})/(?P<day>\w{1,2})/(?P<slug>[\-\d\w]+)/$',
            PhotoDateDetailView.as_view(month_format='%m'),
            name='photo-detail'),
    re_path(r'^photo/(?P<year>\d{4})/(?P<month>[0-9]{2})/(?P<day>\w{1,2})/$',
            PhotoDayArchiveView.as_view(month_format='%m'),
            name='photo-archive-day'),
    re_path(r'^photo/(?P<year>\d{4})/(?P<month>[0-9]{2})/$',
            PhotoMonthArchiveView.as_view(month_format='%m'),
            name='photo-archive-month'),
    re_path(r'^photo/(?P<year>\d{4})/$',
            PhotoYearArchiveView.as_view(),
            name='pl-photo-archive-year'),
    path('photo/',
         PhotoArchiveIndexView.as_view(),
         name='pl-photo-archive'),

    re_path(r'^photo/(?P<slug>[\-\d\w]+)/$',
            PhotoDetailView.as_view(),
            name='pl-photo'),
    path('photolist/',
         PhotoListView.as_view(),
         name='photo-list'),
]

photologue/templates/photologue/gallery_archive.html
{% extends "photologue/root.html" %}
{% load i18n %}

{% block title %}{% trans "Latest photo galleries" %}{% endblock %}

{% block content %}

<div class="row">
    <div class="col-lg-12">
        <h1>{% trans "Latest photo galleries" %}</h1>
    </div>
</div>

<div class="row">

    <aside class="col-md-2">

        <h4>{% trans "Filter by year" %}</h4>
        <ul>
            {% for date in date_list %}
            <li><a href="{% url 'photologue:pl-gallery-archive-year' date.year %}">{{ date|date:"Y" }}</a></li>
            {% endfor %}
        </ul>

    </aside>

    <main class="col-md-10">

        {% if latest %}
        {% for gallery in latest %}
        {% include "photologue/includes/gallery_sample.html" %}
        {% endfor %}
        {% else %}
        <p>{% trans "No galleries were found" %}.</p>
        {% endif %}

    </main>

</div>

{% endblock %}

photologue/templates/photologue/gallery_archive_day.html
{% extends "photologue/root.html" %}
{% load i18n %}

{% block title %}{% blocktrans with show_day=day|date:"d F Y" %}Galleries for {{ show_day }}{% endblocktrans %}{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-lg-12">
            <h1>{% blocktrans with show_day=day|date:"d F Y" %}Galleries for {{ show_day }}{% endblocktrans %}</h1>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
        {% if object_list %}
            {% for gallery in object_list %}
                {% include "photologue/includes/gallery_sample.html" %}
            {% endfor %}
        {% else %}
            <p>{% trans "No galleries were found." %}</p>
        {% endif %}
        </div>
    </div>

    <div><a href="{% url 'photologue:gallery-archive-month' day.year day|date:"m"|lower %}" class="btn btn-outline-secondary">{% trans "View all galleries for month" %}</a></div>

{% endblock %}

photologue/templates/photologue/gallery_archive_month.html
{% extends "photologue/root.html" %}
{% load i18n %}

{% block title %}{% blocktrans with show_month=month|date:"F Y" %}Galleries for {{ show_month }}{% endblocktrans %}{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-lg-12">
            <h1>{% blocktrans with show_month=month|date:"F Y" %}Galleries for {{ show_month }}{% endblocktrans %}</h1>
        </div>
    </div>

    <div class="row">

        <aside class="col-md-2">

            <h4>{% trans "Filter by day" %}</h4>
            <ul>
            {% for date in date_list %}
                <li><a href="{% url 'photologue:gallery-archive-day' date.year date|date:"m"|lower date.day %}">{{ date|date:"d" }}</a></li>
            {% endfor %}
            </ul>

        </aside>

        <main class="col-md-10">

            {% if object_list %}
                {% for gallery in object_list %}
                    {% include "photologue/includes/gallery_sample.html" %}
                {% endfor %}
            {% else %}
                <p>{% trans "No galleries were found." %}</p>
            {% endif %}

            <div><a href="{% url 'photologue:pl-gallery-archive-year' month.year %}" class="btn btn-outline-secondary">{% trans "View all galleries for year" %}</a></div>

        </main>

    </div>

{% endblock %}

photologue/templates/photologue/gallery_archive_year.html
{% extends "photologue/root.html" %}
{% load i18n %}

{% block title %}{% blocktrans with show_year=year|date:"Y" %}Galleries for {{ show_year }}{% endblocktrans %}{% endblock %}

{% block content %}

    <div class="row">
		<div class="col-lg-12">
        	<h1>{% blocktrans with show_year=year|date:"Y" %}Galleries for {{ show_year }}{% endblocktrans %}</h1>
    	</div>
	</div>
	<div class="row">

		<aside class="col-md-2">

			<h4>{% trans "Filter by month" %}</h4>
			<ul>
				{% for date in date_list %}
					<li><a href="{% url 'photologue:gallery-archive-month' date.year date|date:"m"|lower %}">{{ date|date:"F" }}</a></li>
				{% endfor %}
			</ul>

		</aside>

		<main class="col-md-10">

			{% if object_list %}
				{% for gallery in object_list %}
			        {% include "photologue/includes/gallery_sample.html" %}
			    {% endfor %}
			{% else %}
			    <p>{% trans "No galleries were found." %}</p>
			{% endif %}

		    <div><a href="{% url 'photologue:pl-gallery-archive' %}" class="btn btn-outline-secondary">{% trans "View all galleries" %}</a></div>

		</main>

	</div>

{% endblock %}

photologue/templates/photologue/gallery_detail.html
{% extends "photologue/root.html" %}
{% load i18n %}

{% block title %}{{ gallery.title }}{% endblock %}

{% block content %}

<div class="row">
    <div class="col-lg-12">
        <h1>{{ gallery.title }}</h1>
        <p class="text-muted small">{% trans "Published" %} {{ gallery.date_added }}</p>
        {% if gallery.description %}{{ gallery.description|safe }}{% endif %}
        <div class="gallery-list">
            {% for photo in gallery.public %}
            <a href="{{ photo.get_absolute_url }}">
                <img src="{{ photo.get_thumbnail_url }}" class="img-thumbnail" alt="{{ photo.title }}">
            </a>
            {% endfor %}
        </div>
        <div>
            <a href="{% url 'photologue:gallery-list' %}" class="btn btn-outline-secondary">{% trans "View all galleries" %}</a>
        </div>
    </div>
</div>

{% endblock %}

photologue/templates/photologue/gallery_list.html
{% extends "photologue/root.html" %}
{% load i18n %}

{% block title %}{% trans "All galleries" %}{% endblock %}

{% block content %}

<div class="row">
    <div class="col-lg-12">
        <h1>{% trans "All galleries" %}</h1>
    </div>
</div>

{% if object_list %}
{% for gallery in object_list %}
<div class="row">
    <div class="col-lg-12">
        {% include "photologue/includes/gallery_sample.html" %}
    </div>
</div>
{% endfor %}
{% else %}
<div class="row">
    <div class="col-lg-12">{% trans "No galleries were found" %}.</div>
</div>
{% endif %}

{% include "photologue/includes/paginator.html" %}

{% endblock %}

photologue/templates/photologue/photo_archive.html
{% extends "photologue/root.html" %}
{% load i18n %}

{% block title %}{% trans "Latest photos" %}{% endblock %}

{% block content %}

<div class="row">
    <div class="col-lg-12">
        <h1>{% trans "Latest photos" %}</h1>
    </div>
</div>

<div class="row">

    <aside class="col-md-2">

        <h4>{% trans "Filter by year" %}</h4>
        <ul>
            {% for date in date_list %}
            <li><a href="{% url 'photologue:pl-photo-archive-year' date.year %}">{{ date|date:"Y" }}</a></li>
            {% endfor %}
        </ul>

    </aside>

    <main class="col-md-10 photo-list">

        {% if latest %}
        {% for photo in latest %}
        <a href="{{ photo.get_absolute_url }}">
            <img src="{{ photo.get_thumbnail_url }}" class="img-thumbnail" alt="{{ photo.title }}">
        </a>
        {% endfor %}
        {% else %}
        <p>{% trans "No photos were found" %}.</p>
        {% endif %}

    </main>

</div>

{% endblock %}



photologue/templates/photologue/photo_archive_day.html
{% extends "photologue/root.html" %}
{% load i18n %}

{% block title %}{% blocktrans with show_day=day|date:"d F Y" %}Photos for {{ show_day }}{% endblocktrans %}{% endblock %}

{% block content %}

    <div class="row">
		<div class="col-lg-12">
        	<h1>{% blocktrans with show_day=day|date:"d F Y" %}Photos for {{ show_day }}{% endblocktrans %}</h1>
		</div>
	</div>

	{% if object_list %}
		<div class="row">
			<div class="col-lg-12">
		    {% for photo in object_list %}
		        <a href="{{ photo.get_absolute_url }}">
		             <img src="{{ photo.get_thumbnail_url }}" class="img-thumbnail" alt="{{ photo.title }}">
		        </a>
		    {% endfor %}
			</div>
		</div>
	{% else %}
		<p>{% trans "No photos were found" %}.</p>
	{% endif %}

    <div><a href="{% url 'photologue:photo-archive-month' day.year day|date:"m"|lower %}" class="btn btn-outline-secondary">{% trans "View all photos for month" %}</a></div>

{% endblock %}

photologue/templates/photologue/photo_archive_month.html
{% extends "photologue/root.html" %}
{% load i18n %}

{% block title %}{% blocktrans with show_month=month|date:"F Y" %}Photos for {{ show_month }}{% endblocktrans %}{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-lg-12">
            <h1>{% blocktrans with show_month=month|date:"F Y" %}Photos for {{ show_month }}{% endblocktrans %}</h1>
        </div>
    </div>

    <div class="row">

        <aside class="col-md-2">

            <h4>{% trans "Filter by day" %}</h4>
            <ul>
            {% for date in date_list %}
                <li><a href="{% url 'photologue:photo-archive-day' date.year date|date:"m"|lower date.day %}">{{ date|date:"d" }}</a></li>
            {% endfor %}
            </ul>

        </aside>

        <main class="col-md-10">

    		{% if object_list %}
    			<div class="row">
                    <div class="col-lg-12">
    			    {% for photo in object_list %}
    			        <a href="{{ photo.get_absolute_url }}">
    			             <img src="{{ photo.get_thumbnail_url }}" class="img-thumbnail" alt="{{ photo.title }}">
    			        </a>
    			    {% endfor %}
                    </div>
    			</div>
    		{% else %}
    			<p>{% trans "No photos were found" %}.</p>
    		{% endif %}

            <div><a href="{% url 'photologue:pl-photo-archive-year' month.year %}" class="btn btn-outline-secondary">{% trans "View all photos for year" %}</a></div>

        </main>

    </div>

{% endblock %}

photologue/templates/photologue/photo_archive_year.html
{% extends "photologue/root.html" %}
{% load i18n %}

{% block title %}{% blocktrans with show_year=year|date:"Y" %}Photos for {{ show_year }}{% endblocktrans %}{% endblock %}


{% block content %}

    <div class="row">
		<div class="col-lg-12">
        	<h1>{% blocktrans with show_year=year|date:"Y" %}Photos for {{ show_year }}{% endblocktrans %}</h1>
    	</div>
	</div>

	<div class="row">

		<aside class="col-md-2">

			<h4>{% trans "Filter by month" %}</h4>
			<ul>
			{% for date in date_list %}
				<li><a href="{% url 'photologue:photo-archive-month' date.year date|date:"m"|lower %}">{{ date|date:"F" }}</a></li>
			{% endfor %}
			</ul>

		</aside>

		<main class="col-md-10">

			{% if object_list %}
				<div class="row">
					<div class="col-lg-12">
				    {% for photo in object_list %}
				        <a href="{{ photo.get_absolute_url }}">
				             <img src="{{ photo.get_thumbnail_url }}" class="img-thumbnail" alt="{{ photo.title }}">
				        </a>
				    {% endfor %}
					</div>
				</div>
			{% else %}
				<p>{% trans "No photos were found" %}.</p>
			{% endif %}

		    <div><a href="{% url 'photologue:pl-photo-archive' %}" class="btn btn-outline-secondary">{% trans "View all photos" %}</a></div>

		</main>

	</div>

{% endblock %}





photologue/templates/photologue/photo_detail.html
{% extends "photologue/root.html" %}
{% load photologue_tags i18n %}

{% block title %}{{ object.title }}{% endblock %}

{% block content %}

<div class="row">
    <div class="col-lg-12">
        <h1>{{ object.title }}</h1>
        <p class="text-muted small">{% trans "Published" %} {{ object.date_added }}</p>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        {% if object.caption %}<p>{{ object.caption }}</p>{% endif %}
        <a href="{{ object.image.url }}">
            <img src="{{ object.get_display_url }}" class="img-thumbnail" alt="{{ object.title }}">
        </a>
    </div>
    <div class="col-md-6">
        {% if object.public_galleries %}
        <p>{% trans "This photo is found in the following galleries" %}:</p>
        <table>
            {% for gallery in object.public_galleries %}
            <tr>
                <td>{% previous_in_gallery object gallery %}</td>
                <td class="text-center"><a href="{{ gallery.get_absolute_url }}">{{ gallery.title }}</a></td>
                <td>{% next_in_gallery object gallery %}</td>
            </tr>
            {% endfor %}
        </table>
        {% endif %}
    </div>
</div>

{% endblock %}

photologue/templates/photologue/photo_list.html
{% extends "photologue/root.html" %}
{% load i18n %}

{% block title %}{% trans "All photos" %}{% endblock %}

{% block content %}

<div class="row">
    <div class="col-lg-12">
        <h1>{% trans "All photos" %}</h1>
    </div>
</div>
{% if object_list %}
<div class="row">
    <div class="col-lg-12 photo-list">
        {% for photo in object_list %}
        <a href="{{ photo.get_absolute_url }}">
            <img src="{{ photo.get_thumbnail_url }}" class="img-thumbnail" alt="{{ photo.title }}">
        </a>
        {% endfor %}
    </div>
</div>
{% else %}
<div class="row">{% trans "No photos were found" %}.</div>
{% endif %}

{% include "photologue/includes/paginator.html" %}

{% endblock %}

photologue/templates/photologue/root.html
{% extends "base.html" %}